export const API_BASE_URL = 'http://localhost:8080/api';
export const WS_URL = 'http://localhost:8080/ws';

export const ROLES = {
  TENANT: 'TENANT',
  LANDLORD: 'LANDLORD',
  PARTNER: 'PARTNER',
  ADMIN: 'ADMIN'
};

export const MATCH_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  DECLINED: 'DECLINED',
  ROOMMATE_CONFIRMED: 'ROOMMATE_CONFIRMED'
};

export const NOTIFICATION_TYPES = {
  MATCH_REQUEST: 'MATCH_REQUEST',
  MATCH_ACCEPTED: 'MATCH_ACCEPTED',
  MATCH_DECLINED: 'MATCH_DECLINED',
  ROOMMATE_CONFIRMED: 'ROOMMATE_CONFIRMED',
  LISTING_VERIFIED: 'LISTING_VERIFIED',
  NEW_MESSAGE: 'NEW_MESSAGE',
  LANDLORD_CHAT_CREATED: 'LANDLORD_CHAT_CREATED',
  WELCOME: 'WELCOME',
  PARTNER_OFFER: 'PARTNER_OFFER'
};
